### PR TITLE
Formatting and upgrades

### PR DESCRIPTION
**Pull request by barthanssens**
Some indentation fixes, library upgrades (Jetty, Gson...) and removal of superfluous "final"

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Thanks, @barthanssens, will have a look at this. Note that the `final` is always on purpose, to indicate that the variable will not be modified. But we can indeed do without.

**Comment by barthanssens** [comment]
Meanwhile I'm reworking the code a little bit. If all goes well, I'll try to add a Jena datasource.

**Comment by mielvds** [comment]
Thanks for the help! Agreed that the final statements were a bit overdone.

Could you specify the changes you're planning to make in a separate issue? I was, for instance, planning to have a look at content negotiation.

**Comment by barthanssens** [comment]
Ok, I'll close this one and create one or two separate issues :-)
I was working on some refactoring in the servlet (making it a bit more readable) and adding a Jena datasource

**Comment by mielvds** [comment]
We should still merge this right? @RubenVerborgh?

**Comment by barthanssens** [comment]
I'll make another pull request, including your changes on content negotiation.

**Pull request closed without merging**
