### PR TITLE
Upgrades and splitting up some methods

### PR DESCRIPTION
**Pull request by barthanssens**
A bunch of suggested changes

* upgraded Jetty, gson and CLI libraries
* added serialVersionUID to Exceptions
* splitted up init() and doGet() methods in TriplePatternFragmentServlet
* splitted up main() method in the JettyServer
* used more specific Exceptions
* explicit imports instead of 

Most changes are just a matter of preference, so feel free to ignore them if you think they are not useful :-)

### CODE REVIEW

**Comment by mielvds** [comment]
I agree with you preferences :) Merged and part of release 0.0.2

**Comment by mielvds** [comment]
Actually, this doesn't work, since Java is pass by value. controls & meta never get written. WIll fix.

**Comment by mielvds** [comment]
Pass by val should not really be a problem, but something is

**Comment by barthanssens** [comment]
Think it's a merge thing, seems that serialization is done twice in  doGet, probably my bad

**Pull request merged**
