### PR TITLE
Servlet now completely agnostic of the type of LDFs requested

### PR DESCRIPTION
**Pull request by hartig**
As promised in https://github.com/LinkedDataFragments/Server.Java/pull/18#issuecomment-164772329, this PR provides everything to make the servlet completely agnostic of the type of LDFs that the data source supports.

### CODE REVIEW

**Comment by mielvds** [comment]
It probably shouldn't be called TriplePatternFragmentServlet anymore I guess. Aren't you tying everything to the datasource now?

**Comment by hartig** [comment]
@mielvds You are right; it really is a LinkedDataFragmentServlet now. I will rename it and push a commit into this PR.

@RubenVerborgh I know; I am also only "medium-happy" with it. But, as you say, it is already quite an improvement over the existing, TPF-only focused implementation approach. Moreover, note that the actual implementations of the IDataSource interface do not have to deal with the HTTP requests because this is already covered by `AbstractRequestProcessorForTriplePatterns`. Another thing that I should emphasize in this context is that `AbstractRequestProcessorForTriplePatterns` uses the intermediate method `createFragment(String, String, String, long, long)` on purpose. This can be overridden in request processors / data source implementations that are not based on Jena and, thus, it allows for avoiding the overhead of having to i) generate Jena objects and ii) transforming them into some other representation that the backend understands (e.g., Sesame objects).

**Comment by RubenVerborgh** [comment]
@hartig I'm more than medium happy :wink: Great job!

**Comment by hartig** [comment]
@mielvds OK, renaming done.

@RubenVerborgh  ;-)

**Pull request merged**
