### PR TITLE
LDF requests and processors

### PR DESCRIPTION
**Pull request by hartig**
This PR provides the main meat of my refactoring efforts. The functionality related to i) parsing LDF requests and ii) processing such requests is separated out into new interfaces and classes, and the use of these classes is integrated into the existing code base.

### CODE REVIEW

**Comment by mielvds** [comment]
Nice @hartig , this brings us closer to the flexibility LDF is about. The datasource package is kind of crowded though, let me propose the following:
all LinkedDataFragment classes => `org.linkeddatafragments.fragments`
all TriplePatternFragment classes => `org.linkeddatafragments.fragments.triplepattern`
Perhaps remove the servlet class.

`org.linkeddatafragments.ldf` or `org.linkeddatafragments.tpf` could also be possible, less scalable though.

**Comment by hartig** [comment]
OK. I will move the classes as you suggest and add the commits to this PR.

**Comment by RubenVerborgh** [comment]
Full :+1: on this!

**Comment by hartig** [comment]
@mielvds Done! Ah .. hold on ... I just realize how ugly `org.linkeddatafragments.fragments.TPF` as a package name is :-(   Will rename to `org.linkeddatafragments.fragments.tpf`   Just a sec.

**Comment by hartig** [comment]
@mielvds OK, done now.  (Note that I also added source-specific subpackages in `org.linkeddatafragments.datasource`)

**Comment by mielvds** [comment]
Merged! Thanks again. I'll do some minor changes and put out a new release. I'll also rebase the jena-3 branch

**Comment by hartig** [comment]
@mielvds Please wait with the release. I am thinking about a way to make the servlet more generic; i.e., removing the current assumption that the request is a TPF request.

**Comment by mielvds** [comment]
will do

**Comment by hartig** [comment]
Another thing that would be really good to have for what I am planning is to have this server as a Maven artifact (in an online Maven repo).

**Pull request merged**
